---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matillion-agent.fullname" . }}-config
  labels:
    app: matillion
{{- include "matillion-agent.labels" . | nindent 4 }}
stringData:
  OAUTH_CLIENT_ID: {{ required "config.oauthClientId is required" .Values.config.oauthClientId | quote }}
  OAUTH_CLIENT_SECRET: {{ required "config.oauthClientSecret is required" .Values.config.oauthClientSecret | quote }}