{{- if .Values.modules.adapter.enabled | default .Values.adapter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}-adapter
  labels:
  {{- include "prometheus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.adapter.type }}
  selector:
    app: prometheus-adapter
  {{- include "prometheus.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.adapter.ports | toYaml | nindent 2 }}
{{- end }}