{{- if or (.Values.modules.adapter.enabled | default .Values.adapter.enabled) (.Values.modules.api.enabled | default .Values.api.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prometheus.fullname" . }}-custom-metrics-server-resources
  labels:
  {{- include "prometheus.labels" . | nindent 4 }}
rules:
- apiGroups:
  - custom-metrics.metrics.k8s.io
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - list
{{- end }}