{{- if .Values.modules.prometheus.enabled | default .Values.prometheus.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prometheus.fullname" . }}-pod-list-binding
  labels:
  {{- include "prometheus.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "prometheus.fullname" . }}-pod-list'
subjects:
- kind: ServiceAccount
  name: '{{ include "prometheus.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'
{{- end }}
